name: CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        django-version: [2.2, 3.0, 3.1]
        gdal-version: [gdal2, gdal3]

    steps:
      - if: matrix.gdal-version == 'gdal2'
        run: sudo apt-get install binutils libproj-dev gdal-bin
      - if: matrix.gdal-version == 'gdal3'
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install binutils libproj-dev gdal-bin
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: actions/checkout@v2
      - run: python -m pip install Django==${{ matrix.django-version }}
      - run: python manage.py test
