name: CI
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6]
        django-version: [2.2, 3.0, 3.1]

    steps:
      - run: sudo apt-get install binutils libproj-dev gdal-bin
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - run: python -m pip install Django==${{ matrix.django-version }}
      - run: python manage.py test
